version = 5.4.0
archive_dir = /etc/letsencrypt/archive/sucatabet.com.br
cert = /etc/letsencrypt/live/sucatabet.com.br/cert.pem
privkey = /etc/letsencrypt/live/sucatabet.com.br/privkey.pem
chain = /etc/letsencrypt/live/sucatabet.com.br/chain.pem
fullchain = /etc/letsencrypt/live/sucatabet.com.br/fullchain.pem
[renewalparams]
account = 60268a4491f0f1962fe78efe1b3a69f8
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
sucatabet.com.br = /var/www/certbot
www.sucatabet.com.br = /var/www/certbot
