name: Deploy SucataBet
on:
  push:
    branches:
      - main
concurrency:
  group: deploy-production
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Deploy Script on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USER }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          port: 22
          script: |
            cd /var/www/sucatabet
            git pull origin main
            chmod +x scripts/backup-db.sh
            bash scripts/backup-db.sh
            docker compose -f docker-compose.prod.yml build --no-cache --build-arg NEXT_PUBLIC_API_URL=https://sucatabet.com.br/api
            docker compose -f docker-compose.prod.yml up -d
            docker compose -f docker-compose.prod.yml exec -T api npx prisma migrate deploy --schema=apps/api/prisma/schema.prisma
            docker image prune -f
