name: Deploy SucataBet
on:
  push:
    branches:
      - main
concurrency:
  group: deploy-production
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Deploy Script on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USER }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          port: 22
          script: |
            cd /var/www/sucatabet
            git fetch origin main
            git reset --hard origin/main
            chmod +x scripts/backup-db.sh
            bash scripts/backup-db.sh
            # Build and Up API first (lighter and needed for migrations)
            docker compose -f docker-compose.prod.yml build api --build-arg NEXT_PUBLIC_API_URL=https://sucatabet.com.br/api
            docker compose -f docker-compose.prod.yml up -d api
            
            # Run migrations
            docker compose -f docker-compose.prod.yml run --rm api npx prisma migrate deploy --schema=apps/api/prisma/schema.prisma
            
            # Build and Up Web (heavier)
            docker compose -f docker-compose.prod.yml build web --build-arg NEXT_PUBLIC_API_URL=https://sucatabet.com.br/api
            docker compose -f docker-compose.prod.yml up -d web
            
            docker image prune -f
